"use strict";
// Code generated by protoc-gen-tstypes. DO NOT EDIT.
Object.defineProperty(exports, "__esModule", { value: true });
exports.OptionValue = exports.DeviceType = void 0;
var DeviceType;
(function (DeviceType) {
    DeviceType["UNKNOWN_DEVICE"] = "UNKNOWN_DEVICE";
    DeviceType["U2F_DEVICE"] = "U2F_DEVICE";
    DeviceType["FIDO2_DEVICE"] = "FIDO2_DEVICE";
})(DeviceType = exports.DeviceType || (exports.DeviceType = {}));
var OptionValue;
(function (OptionValue) {
    OptionValue["DEFAULT_OPTION"] = "DEFAULT_OPTION";
    OptionValue["TRUE"] = "TRUE";
    OptionValue["FALSE"] = "FALSE";
})(OptionValue = exports.OptionValue || (exports.OptionValue = {}));
//# sourceMappingURL=fido2.js.map