"use strict";
// Code generated by protoc-gen-tsrpc DO NOT EDIT.
// InputID: 2c5317c90471dee9f8a60cb47b72d171f45d63e0
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.FIDO2Service = void 0;
const grpc = __importStar(require("@grpc/grpc-js"));
const events_1 = require("events");
class FIDO2Service extends events_1.EventEmitter {
    constructor(serviceFn) {
        super();
        this.serviceFn = serviceFn;
    }
    service() {
        if (!this.client) {
            this.client = this.serviceFn();
        }
        return this.client;
    }
    emitError(err) {
        switch (err.code) {
            case grpc.status.PERMISSION_DENIED:
            case grpc.status.UNAUTHENTICATED:
                this.emit('unauthenticated', err);
                break;
            case grpc.status.UNAVAILABLE:
                this.emit('unavailable', err);
                break;
            default:
                this.emit('error', err);
                break;
        }
    }
    Devices(req) {
        return new Promise((resolve, reject) => {
            this.service().Devices(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    DeviceInfo(req) {
        return new Promise((resolve, reject) => {
            this.service().DeviceInfo(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    DeviceType(req) {
        return new Promise((resolve, reject) => {
            this.service().DeviceType(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    MakeCredential(req) {
        return new Promise((resolve, reject) => {
            this.service().MakeCredential(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    SetPIN(req) {
        return new Promise((resolve, reject) => {
            this.service().SetPIN(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    Reset(req) {
        return new Promise((resolve, reject) => {
            this.service().Reset(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    RetryCount(req) {
        return new Promise((resolve, reject) => {
            this.service().RetryCount(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    Assertion(req) {
        return new Promise((resolve, reject) => {
            this.service().Assertion(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    CredentialsInfo(req) {
        return new Promise((resolve, reject) => {
            this.service().CredentialsInfo(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    Credentials(req) {
        return new Promise((resolve, reject) => {
            this.service().Credentials(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    RelyingParties(req) {
        return new Promise((resolve, reject) => {
            this.service().RelyingParties(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    GenerateHMACSecret(req) {
        return new Promise((resolve, reject) => {
            this.service().GenerateHMACSecret(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    HMACSecret(req) {
        return new Promise((resolve, reject) => {
            this.service().HMACSecret(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
}
exports.FIDO2Service = FIDO2Service;
//# sourceMappingURL=fido2.service.js.map