"use strict";
// Code generated by protoc-gen-tsrpc DO NOT EDIT.
// InputID: f35e5bb6150264d68c83f1a9f2aebe6584ea6299
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeysService = void 0;
const grpc = __importStar(require("@grpc/grpc-js"));
const events_1 = require("events");
const ts_log_1 = require("ts-log");
class KeysService extends events_1.EventEmitter {
    constructor(serviceFn) {
        super();
        this.log = ts_log_1.dummyLogger;
        this.serviceFn = serviceFn;
    }
    service() {
        if (!this.client) {
            this.client = this.serviceFn();
        }
        return this.client;
    }
    emitError(err) {
        switch (err.code) {
            case grpc.status.PERMISSION_DENIED:
            case grpc.status.UNAUTHENTICATED:
                this.emit('unauthenticated', err);
                break;
            case grpc.status.UNAVAILABLE:
                this.emit('unavailable', err);
                break;
            default:
                this.emit('error', err);
                break;
        }
    }
    keyGenerate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyGenerate');
            this.service().keyGenerate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keys(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keys');
            this.service().keys(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    key(req) {
        return new Promise((resolve, reject) => {
            this.log.info('key');
            this.service().key(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyImport(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyImport');
            this.service().keyImport(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyExport(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyExport');
            this.service().keyExport(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    keyRemove(req) {
        return new Promise((resolve, reject) => {
            this.log.info('keyRemove');
            this.service().keyRemove(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    sign(req) {
        return new Promise((resolve, reject) => {
            this.log.info('sign');
            this.service().sign(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    signFile() {
        this.log.info('signFile');
        return this.service().signFile();
    }
    signStream() {
        this.log.info('signStream');
        return this.service().signStream();
    }
    verify(req) {
        return new Promise((resolve, reject) => {
            this.log.info('verify');
            this.service().verify(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    verifyFile() {
        this.log.info('verifyFile');
        return this.service().verifyFile();
    }
    verifyStream() {
        this.log.info('verifyStream');
        return this.service().verifyStream();
    }
    verifyDetached(req) {
        return new Promise((resolve, reject) => {
            this.log.info('verifyDetached');
            this.service().verifyDetached(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    verifyDetachedFile(req) {
        return new Promise((resolve, reject) => {
            this.log.info('verifyDetachedFile');
            this.service().verifyDetachedFile(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    verifyDetachedStream(req) {
        return new Promise((resolve, reject) => {
            this.log.info('verifyDetachedStream');
            this.service().verifyDetachedStream(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    encrypt(req) {
        return new Promise((resolve, reject) => {
            this.log.info('encrypt');
            this.service().encrypt(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    encryptStream() {
        this.log.info('encryptStream');
        return this.service().encryptStream();
    }
    encryptFile() {
        this.log.info('encryptFile');
        return this.service().encryptFile();
    }
    decrypt(req) {
        return new Promise((resolve, reject) => {
            this.log.info('decrypt');
            this.service().decrypt(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    decryptStream() {
        this.log.info('decryptStream');
        return this.service().decryptStream();
    }
    decryptFile() {
        this.log.info('decryptFile');
        return this.service().decryptFile();
    }
    sigchain(req) {
        return new Promise((resolve, reject) => {
            this.log.info('sigchain');
            this.service().sigchain(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    statement(req) {
        return new Promise((resolve, reject) => {
            this.log.info('statement');
            this.service().statement(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    statementCreate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('statementCreate');
            this.service().statementCreate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    statementRevoke(req) {
        return new Promise((resolve, reject) => {
            this.log.info('statementRevoke');
            this.service().statementRevoke(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    user(req) {
        return new Promise((resolve, reject) => {
            this.log.info('user');
            this.service().user(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userSearch(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userSearch');
            this.service().userSearch(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userService(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userService');
            this.service().userService(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userSign(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userSign');
            this.service().userSign(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    userAdd(req) {
        return new Promise((resolve, reject) => {
            this.log.info('userAdd');
            this.service().userAdd(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    search(req) {
        return new Promise((resolve, reject) => {
            this.log.info('search');
            this.service().search(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    secret(req) {
        return new Promise((resolve, reject) => {
            this.log.info('secret');
            this.service().secret(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    secretSave(req) {
        return new Promise((resolve, reject) => {
            this.log.info('secretSave');
            this.service().secretSave(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    secretRemove(req) {
        return new Promise((resolve, reject) => {
            this.log.info('secretRemove');
            this.service().secretRemove(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    secrets(req) {
        return new Promise((resolve, reject) => {
            this.log.info('secrets');
            this.service().secrets(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    pull(req) {
        return new Promise((resolve, reject) => {
            this.log.info('pull');
            this.service().pull(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    push(req) {
        return new Promise((resolve, reject) => {
            this.log.info('push');
            this.service().push(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    wormhole() {
        this.log.info('wormhole');
        return this.service().wormhole();
    }
    authSetup(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authSetup');
            this.service().authSetup(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authVault(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authVault');
            this.service().authVault(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authUnlock(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authUnlock');
            this.service().authUnlock(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authLock(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authLock');
            this.service().authLock(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authReset(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authReset');
            this.service().authReset(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authRecover(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authRecover');
            this.service().authRecover(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    runtimeStatus(req) {
        return new Promise((resolve, reject) => {
            this.log.info('runtimeStatus');
            this.service().runtimeStatus(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    rand(req) {
        return new Promise((resolve, reject) => {
            this.log.info('rand');
            this.service().rand(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    randPassword(req) {
        return new Promise((resolve, reject) => {
            this.log.info('randPassword');
            this.service().randPassword(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authProvision(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authProvision');
            this.service().authProvision(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authDeprovision(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authDeprovision');
            this.service().authDeprovision(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authProvisions(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authProvisions');
            this.service().authProvisions(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    authPasswordChange(req) {
        return new Promise((resolve, reject) => {
            this.log.info('authPasswordChange');
            this.service().authPasswordChange(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    vaultAuth(req) {
        return new Promise((resolve, reject) => {
            this.log.info('vaultAuth');
            this.service().vaultAuth(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    vaultSync(req) {
        return new Promise((resolve, reject) => {
            this.log.info('vaultSync');
            this.service().vaultSync(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    vaultUnsync(req) {
        return new Promise((resolve, reject) => {
            this.log.info('vaultUnsync');
            this.service().vaultUnsync(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    vaultStatus(req) {
        return new Promise((resolve, reject) => {
            this.log.info('vaultStatus');
            this.service().vaultStatus(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    vaultUpdate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('vaultUpdate');
            this.service().vaultUpdate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    collections(req) {
        return new Promise((resolve, reject) => {
            this.log.info('collections');
            this.service().collections(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    documents(req) {
        return new Promise((resolve, reject) => {
            this.log.info('documents');
            this.service().documents(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    documentDelete(req) {
        return new Promise((resolve, reject) => {
            this.log.info('documentDelete');
            this.service().documentDelete(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    configGet(req) {
        return new Promise((resolve, reject) => {
            this.log.info('configGet');
            this.service().configGet(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    configSet(req) {
        return new Promise((resolve, reject) => {
            this.log.info('configSet');
            this.service().configSet(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    adminSignURL(req) {
        return new Promise((resolve, reject) => {
            this.log.info('adminSignURL');
            this.service().adminSignURL(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    adminCheck(req) {
        return new Promise((resolve, reject) => {
            this.log.info('adminCheck');
            this.service().adminCheck(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    channels(req) {
        return new Promise((resolve, reject) => {
            this.log.info('channels');
            this.service().channels(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    channelCreate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('channelCreate');
            this.service().channelCreate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    messagePrepare(req) {
        return new Promise((resolve, reject) => {
            this.log.info('messagePrepare');
            this.service().messagePrepare(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    messageCreate(req) {
        return new Promise((resolve, reject) => {
            this.log.info('messageCreate');
            this.service().messageCreate(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    messages(req) {
        return new Promise((resolve, reject) => {
            this.log.info('messages');
            this.service().messages(req, (err, resp) => {
                if (err) {
                    reject(err);
                    this.emitError(err);
                    return;
                }
                resolve(resp);
            });
        });
    }
    relay(req) {
        this.log.info('relay');
        return this.service().relay(req);
    }
}
exports.KeysService = KeysService;
//# sourceMappingURL=keys.service.js.map